Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.network "forwarded_port", guest: 4201, host: 4201
  config.vm.network "forwarded_port", guest: 9091, host: 9091
  config.vm.synced_folder "../", "/tohr"

  config.vm.provision "shell", inline: <<-SHELL
    echo "###########"
    echo "Update package lists..."
    echo "###########"
    apt-get update

    echo "###########"
    echo "Install node"
    echo "###########"
    wget -qO- https://deb.nodesource.com/setup_12.x | sudo -E bash -
    sudo apt-get install -y nodejs
    sudo apt-get install -y build-essential

    echo "###########"
    echo "Install transmission-daemon"
    echo "###########"
    sudo apt-get install -y transmission-daemon
    sudo service transmission-daemon stop
    sudo cp /tohr/vagrant/vagrant-settings.json /etc/transmission-daemon/settings.json
    sudo service transmission-daemon start

    echo "###########"
    echo "Set the vagrant user as the owner of files in /tohr"
    echo "###########"
    sudo chown -R vagrant /tohr
    mkdir -p /home/vagrant/films
    mkdir -p /home/vagrant/musics
    mkdir -p /home/vagrant/series
    mkdir -p /home/vagrant/other

    sudo chown -R vagrant /home/vagrant/films
    sudo chown -R vagrant /home/vagrant/musics
    sudo chown -R vagrant /home/vagrant/series
    sudo chown -R vagrant /home/vagrant/other
  SHELL

end
